name: guitarfinetune
base: core24
version: "11.3.15"
summary: Guitar fine-tuning tool
description: |
  guitarfinetune
  compares the current frequencies of the guitar strings
  to the frequencies that the strings should have.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:
  armhf:
  ppc64el:
  s390x:
  # amd64:
  #   build-on: [amd64]
  #   build-for: [amd64]
  # arm64:
  #   build-on: [arm64]
  #   build-for: [arm64]
  # armhf:
  #   build-on: [armhf]
  #   build-for: [armhf]
  # ppc64el:
  #   build-on: [ppc64el]
  #   build-for: [ppc64el]
  # riscv64:
  #   build-on: [riscv64]
  #   build-for: [riscv64]
  # s390x:
  #   build-on: [s390x]
  #   build-for: [s390x]
  # i386:
  #   build-on: [amd64, i386]
  #   build-for: [i386]
  # powerpc:
  #   build-on: [amd64, powerpc]
  #   build-for: [powerpc]

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/ekrogh/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
      - ocl-icd-opencl-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - libavcodec60
      - libavutil58
      - libcodec2-1.2
      - libdav1d7
      - libgsm1
      - libhwy1t64
      - libjack-jackd2-0
      - libjxl0.7
      - libnuma1
      - librav1e0
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libsvtav1enc1d1
      - libswresample4
      - libx264-164
      - libx265-199
      - libxvidcore4
      - libzvbi0t64
      - ocl-icd-libopencl1
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libasound*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libavcodec*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libavutil*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcodec*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdav1d*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdnsfile*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libFLAC*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgsm*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libhwy.so.1*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack.so.0*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjxl*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libnuma.so.1*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libOpenCL*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/librav1e*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamplerate*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libshine*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsnappy*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsoxr*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libspeex*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libSvtAv1Enc*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsvtav1enc1d1*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libswresample*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvorbis*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libx264*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libx265*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxvidcore*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libzvbi.so.0*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/ocl-icd-libopencl1*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
      
  guitarfinetune:
    after: [alsa-mixin]
    source: .
    plugin: make
    override-build: |
      make clean -j8 CONFIG=Release -C Builds/LinuxMakefile
      make -j8 CONFIG=Release -C Builds/LinuxMakefile
      cp -f Builds/LinuxMakefile/build/GuitarFineTune $SNAPCRAFT_PART_INSTALL/guitarfinetune
    build-packages:
      - libasound2-dev
      - libc++-18-dev
      - libcurlpp-dev
      - libfontconfig-dev
      - libgcc-s1
      - libgtk-3-dev
      - libm17n-dev
      - libstdc++6
      - libwebkit2gtk-4.1-dev
    stage-packages:
      - glib-networking
      - libcom-err2
      - libcurl4
      - libffi8
      - libfontconfig1
      - libfreetype6
      - libgcc-s1
      - libgmp10
      - libgnutls30
      - libgssapi-krb5-2
      - libhogweed6
      - libidn2-0
      - libk5crypto3
      - libkeyutils1
      - libkrb5-3
      - libkrb5support0
      - libldap2
      - libm17n-0
      - libnettle8t64
      - libnghttp2-14
      - libp11-kit0
      - libpng16-16t64
      - libproxy1v5
      - libpsl5
      - librtmp1
      - libsasl2-2
      - libssh-4
      - libssl3t64
      - libstdc++6
      - libtasn1-6
      - libunistring5
      - libz1
      - libzstd1

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
   
environment:
  ALWAYS_USE_PULSEAUDIO: '1'
    
apps:
  guitarfinetune:
    extensions: [gnome]
    command-chain: ["snap/command-chain/alsa-launch"]
    command: guitarfinetune
    plugs:
      - alsa
      - audio-record
      - pulseaudio
      - audio-playback
      - home
