name: guitarfinetune
base: core22
version: "10.15.10"
summary: Guitar fine-tuning tool
description: |
  guitarfinetune
  compares the current frequencies of the guitar strings
  to the frequencies that the strings should have.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: armhf
    build-for: armhf
  - build-on: i386
    build-for: i386
  - build-on: powerpc
    build-for: powerpc
  - build-on: ppc64el
    build-for: ppc64el
  - build-on: riscv64
    build-for: riscv64
  - build-on: s390x
    build-for: s390x

# architectures: [amd64, s390x, arm64, armhf]
# architectures:
#   - build-on: amd64
#     run-on: amd64

#   - build-on: s390x
#     run-on: s390x

#   - build-on: arm64
#     run-on: arm64

#   - build-on: armhf
#     run-on: armhf

#   - build-on: i386
#     run-on: i386

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/ekrogh/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libasound*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdnsfile*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libFLAC*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjack*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpulse*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamplerate*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libspeex*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvorbis*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio
      
  guitarfinetune:
    after: [alsa-mixin]
    plugin: nil
    source: .
    override-build: |
      g++ --version
      cd Builds/LinuxMakefile/
      pwd
      make clean
      make CONFIG=Release
      cp build/GuitarFineTune $SNAPCRAFT_PART_INSTALL/guitarfinetune
    build-packages:
      - g++
      - make
      - git
      - libfreetype6-dev
      - libx11-dev
      - libxcomposite-dev
      - libxext-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libxcursor-dev
      - libgtk-3-dev
      - libwebkit2gtk-4.0-dev
      - libglu1-mesa-dev
      - mesa-common-dev
      - libasound2-dev
      - libcurl4-openssl-dev
      - freeglut3-dev
      - ladspa-sdk
    stage-packages:
      - libxfixes3
      - libmd0
      - libsqlite3-0
      - libffi7
      - libkeyutils1
      - libtasn1-6
      - libp11-kit0
      - libkrb5support0
      - libcomerr2
      - libk5crypto3
      - libkrb5-3
      - libgmp10
      - libgnutls30
      - libunistring2
      - libssh-4
      - libidn2-0
      - libasn1-8-heimdal
      - libfreetype6
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
      - libsdl-net1.2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libopenal1
      - libsndio7.0
      - libspeex1
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon0
      - libglu1-mesa
      - libasound2
      - libasyncns0
      - libbsd0
      - libdbus-1-3
      - libflac8
      - libgcc1
      - libgcrypt20
      - libgl1
      - libglvnd0
      - libglx0
      - libgpg-error0
      - liblz4-1
      - liblzma5
      - libncursesw5
      - libogg0
      - libpng16-16
      - libpulse0
      - libsdl1.2debian
      - libslang2
      - libsndfile1
      - libstdc++6
      - libsystemd0
      - libtinfo5
      - libvorbis0a
      - libvorbisenc2
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - zlib1g
      - freeglut3

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa

    
apps:
  guitarfinetune:
    extensions: [gnome]
    command-chain: ["snap/command-chain/alsa-launch"]
    command: guitarfinetune
    plugs:
      - alsa
      - audio-record
      - pulseaudio
      - audio-playback
      - home
